### ISSUE TITLE
Link to repo in package.json

### ISSUE THREAD

**Issue by kartsims** [phanan/vue-google-signin-button#1]
I found your library on NPM and had to search to find your Github repo, so much effort ;-)

You could add it to `package.json`... Here is a link to NPM docs, so that you don't even have to search

https://docs.npmjs.com/files/package.json#repository

Great job with the plugin btw !

**Comment by phanan** [comment]
Woots… I forgot to "watch" this repo and missed this issue. Thanks, will do!
