### ISSUE TITLE
Having trouble to add api:client.js

### ISSUE THREAD

**Issue by umervservices** [phanan/vue-google-signin-button#10]
Having trouble to add https://apis.google.com/js/api:client.js in a script tag, I have the following directory structure:

/index.html
   src/
       /components/signupGoogle.vue (google sign in component)
       /views/signup.vue (signup view where signupGoogle added)
       App.vue
       main.js

Can you guide where and how to add the script tag?

**Comment by SeedyROM** [comment]
Add the script in the head of your index.html file.
