### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by h-matsuo** [phanan/vue-google-signin-button#31]
Hi, thanks for your awesome work.

I'm developing an intranet website using Nuxt.js.
I've configured the vue-google-signin-button component in a Nuxt's basic way, but it shows `Cannot read property 'props' of undefined` error and doesn't work.

Where am I wrong?
Are there any extra steps needed when using with Nuxt.js?

### To reproduce

https://codesandbox.io/s/vue-google-signin-button-cannot-read-property-props-of-undefined-l4lxb

The above code will result in:

![image](https://user-images.githubusercontent.com/19528041/65060623-30a4f080-d9b3-11e9-897a-980d961b73b9.png)

---

#### Environment

- nuxt: v2.9.2
- vue-google-signin-button: v1.0.4

**Comment by thomasedwards** [comment]
I get a different error when I use that link.

Have you done this?

>Important: `https://apis.google.com/js/api:client.js` must be included as a <script> in your web app, as this plugin depends on it.

**Comment by h-matsuo** [comment]
@thomasedwards Thanks for the reply.

> Have you done this?
> 
> > Important: https://apis.google.com/js/api:client.js must be included as a <script> in your web app, as this plugin depends on it.

Yes.

```ts
// nuxt.config.ts L.19
    script: [{ src: "https://apis.google.com/js/api:client.js" }]
```

The above configuration surely includes `<script>` in `<head>`:

![image](https://user-images.githubusercontent.com/19528041/65169769-3ae1f000-da82-11e9-933c-ab043fbd13c0.png)

> I get a different error when I use that link.

What error did you get?

I got this error with Google Chrome, but it may claim a different error message if you use other browser. For example, when opened with Safari, the error message is `undefined is not an object (evaluating 'Ctor.options.props')`.

**Comment by thomasedwards** [comment]
Ah yeah that’s the message I got in Firefox.

I don’t know the internals of Nuxt well enough at all, but we are using this with Nuxt. We are using a plugin to import it:

    import Vue from 'vue'
    import GSignInButton from 'vue-google-signin-button'

    Vue.use(GSignInButton)

Not sure if this is required for it to work with Nuxt?

**Comment by h-matsuo** [comment]
OK problem solved. I made two mistakes:

**1\. I should import `vue-google-signin-button` as a plugin globally, not as a custom component locally.**

At first, I imported it within an `index.vue` using [local registration](https://vuejs.org/v2/guide/components-registration.html#Local-Registration) method:

```vue
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component({
  components: {
    GSignInButton: () => import('vue-google-signin-button')
  }
})
export default class Page extends Vue {
  // omitted
}
</script>
```

But I should create the file `plugins/vue-google-signin-button.ts` and import it from `nuxt.config.ts` as a [vue plugin](https://nuxtjs.org/guide/plugins#vue-plugins):

```ts
// plugins/vue-google-signin-button.ts
import Vue from 'vue'
import GSignInButton from 'vue-google-signin-button'
Vue.use(GSignInButton)
```

```ts
// nuxt.config.ts
plugins: [ '@/plugins/vue-google-signin-button.ts' ]
```

I thought the above two code will do the same thing... I misunderstood.

**2\. I should refer the component with kebab-case, not camel case.**

The following claims `Unknown custom element` error.

```vue
<GSignInButton
  :params="googleSignInParams"
  @success="onSignInSuccess"
  @error="onSignInError"
>
  Sign in with Google
</GSignInButton>
```

This works fine:

```vue
<g-signin-button
  :params="googleSignInParams"
  @success="onSignInSuccess"
  @error="onSignInError"
>
  Sign in with Google
</g-signin-button>
```

I also misunderstood that there's no difference between two cases.

@thomasedwards Thanks!

**Comment by thomasedwards** [comment]
Ah yes! I have eslint correcting my lack-of-kebab case because I too have had this problem more than once... thanks for documenting, may help Nuxters in the future.
