### ISSUE TITLE
Is User Logout option available in this plugin?

### ISSUE THREAD

**Issue by naveenkumarmark** [phanan/vue-google-signin-button#32]
HI All, Is Sign Out option available for this plugin or do I need to do it by maintaining the user session?

**Comment by thomasedwards** [comment]
There’s no such thing as “sign out” because to be signed out would be sign out of Google.

[You can disconnect and revoke permissions](https://developers.google.com/identity/sign-in/web/disconnect), but if you just want the behaviour of being ‘signed out’ on your app, then that happens on your app.

**Comment by phanan** [comment]
You'll need to handle signing out on your own.
