### ISSUE TITLE
popup_blocked_by_browser error

### ISSUE THREAD

**Issue by naveenkumarmark** [phanan/vue-google-signin-button#33]
I get this exception sometime saying `popup_blocked_by_browser`
Error message is  { error: "popup_blocked_by_browser" }.
How to fix this one?

**Comment by thomasedwards** [comment]
Sadly you can’t, you can only handle it. Perhaps show your user a message like “You need to enabled pop-ups to sign in.”

**Comment by phanan** [comment]
What @thomasedwards said :) Thanks.
