### ISSUE TITLE
Getting error for [g-signin-button] "https://apis.google.com/js/api:client.js" needs to be included as a <script>.

### ISSUE THREAD

**Issue by aliissa** [phanan/vue-google-signin-button#4]
I keep on getting the error [g-signin-button] "https://apis.google.com/js/api:client.js" needs to be included as a <script>, although I added this <script type="javascript" src="https://apis.google.com/js/api:client.js"></script> before the script of the component.

**Comment by scottleblanc** [comment]
Same issue here using Vue2

**Comment by juanbrujo** [comment]
adding `<script src="https://apis.google.com/js/api:client.js"></script>` to the `<head></head>` fixed this

**Comment by ckathleen** [comment]
same issue
