### ISSUE TITLE
Use Google sign in original branding buttons

### ISSUE THREAD

**Issue by GotaloveCode** [phanan/vue-google-signin-button#48]
This is more of a feature request.
According to google you can no longer randomly brand your google sign in button. [https://developers.google.com/identity/branding-guidelines#top_of_page](https://developers.google.com/identity/branding-guidelines#top_of_page)
This is a request to have the google sign in button component have this as a default. 

Thank you for the great package.

**Comment by phanan** [comment]
> You can no longer randomly brand your google sign in button

Nor should you :) You can still totally style your button to follow Google's brand guideline though.

**Comment by GotaloveCode** [comment]
I was requesting that you have the button with the default google login branding since it generates a plain button

**Comment by phanan** [comment]
And I was saying that it's not the job of the plugin. Though restricted by the brand guideline, the website can still customize the look and feel of the button in virtually unlimited ways.
