### ISSUE TITLE
Need migration to the new Google Identity Services library

### ISSUE THREAD

**Issue by bearmini** [phanan/vue-google-signin-button#56]
I've got a mail from Google Developers like below:

> Hello Google Developer,
> 
> You are receiving this message as a reminder that one or more of your web applications uses the [legacy Google Sign-In web solution](https://notifications.google.com/g/p/AKWoLQgfqXoozA5fGu_yAHcAwGM24f_TgzfNVVZjMyUGcorEG9BSM5Be66POKoihGXekRo_d6CyCfC3XtZn7d6T0vYdYplcHxlUcm62eYGJ7HcpOEC0A4P5jayqi7C--NS0fvLtNp5DxJPGW). Our [announced plan](https://notifications.google.com/g/p/AKWoLQh7_IU0mpq9kUbLTFwzVadkL2S8Ni2sYXbPXtvK0XRzpBWILYJoXgcoXFVez2wmDrdyEp79pMe1hOLMexLIV8_7FPlPbNZ4lwDcZsO0oNCpNFmeXvx2WuPd3nw-6uuDGrkg6LEMUCNONdoaXyi3Cq7JTQ) stated that authentication support for the Google Sign-In JavaScript platform library will no longer be supported after March 31, 2023.
>
> After March 31, 2023, migration to the new [Google Identity Services](https://notifications.google.com/g/p/AKWoLQgS7WSGVwHQ46T3YcY1dXkDAFfkWq-GojaGtONztgFjDXXS2mna01U1l6GTYJHF4lIkFRFowpZi3-S3xwnbpMRd-tYOhzoMsLIr20iD2j--IjxVLAS6UhS0yql0JqU9) will be necessary to sign in customers using their Google Account to your platform. The SDK will use the new Sign In With Google client library.

The mail contains App name and Client ID for my web app which uses `vue-google-signin-button` component.

Do you have any plan to migrate to the new library?

**Comment by bearmini** [comment]
I have decided to use https://github.com/EduardoVa/vue-google-identity-login-btn

**Comment by Ashutoshkaushik01** [comment]
@bearmini is this the migrated one ????

**Comment by bearmini** [comment]
> @bearmini is this the migrated one ????

@Ashutoshkaushik01 I use [vue-google-identity-login-btn](https://github.com/EduardoVa/vue-google-identity-login-btn) for my project and it seems to use the new Google Identity Services.

**Comment by Ashutoshkaushik01** [comment]
@bearmini okay Thanks, mate :)
