### ISSUE TITLE
Token expiration 1 hour

### ISSUE THREAD

**Issue by Dmitry1987** [phanan/vue-google-signin-button#6]
Hi, thanks for the nice module,
do you know if it's possible to obtain a token for more than 1 hour?  the 'id_token' always expires... and there's no "refresh_token" in the response I get from google :( .

**Comment by camhart** [comment]
Just call reloadAuthResponse on the google user object.

https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse

I don't think this is related to the vue plugin.
